# https://travis-ci.org/#!/phlax/bazeldev

dist: bionic

script:
  - git clone -b fix_wasm_example https://github.com/PiotrSikora/envoy
  - cd envoy
  - ./ci/run_envoy_docker.sh bazel build //examples/wasm:envoy_filter_http_wasm_example.wasm
  - ls build_output
