# https://travis-ci.org/#!/phlax/bazeldev

dist: bionic

script:
  - git clone -b docs-add-wasm-sandbox-docs https://github.com/phlax/envoy
  - cd envoy/examples/wasm
  # - docker-compose -f docker-compose-wasm.yaml up wasm_compile
  # - sudo ls -alh wasm
  - ./verify.sh
